### ISSUE TITLE
Deducing organismid

### ISSUE THREAD

**Issue by David-Guillot** [sgmap/meteor-assemblee-nationale#1]
Hi,

Your README says that the organismId cannot be predicted. Here is a way not to predict it, but to deduce it in order to avoid passing it as an argument:

1. The bill timeline ("Dossier législatif", e.g. [1st Macron law project](http://www.assemblee-nationale.fr/14/dossiers/croissance_activite.asp) ) contains, just after the link to a text, a link to the organism in charge of examining/amending the text (e.g. for [the "commission spéciale au fond"](http://www2.assemblee-nationale.fr/instances/fiche/OMC_PO704848) )
2. The URL of this page contains the ID of the organism in Assemblée Nationale information system ("PO704848") ; but this is not yet what we're looking for
3. Here you can use the great work of @regardscitoyens: ParlAPI exposes details about organisms (e.g. http://parlapi.fr/rest/an/organes/PO704848) where the `abbreviation` field finally contains "CSCRACTIV"

Hope this can help, especially for Fiches de Banc ;)

**Comment by MattiSG** [comment]
Great, thank you very much for documenting this! The API could be simplified by implementing this behaviour 😃

This package is not actively maintained anymore, since we have no active product using it, but I would happily review a PR adding an “autodetection” feature for `organismId` and decreasing the arity of `getAmendements`.

**Comment by David-Guillot** [comment]
Cleaning up my open issues, I won't do anything about this one for sure.
